pw.x < PWINPUT.1xm > LOG.1xm
pw.x < PWINPUT.1xp > LOG.1xp
pw.x < PWINPUT.1ym > LOG.1ym
pw.x < PWINPUT.1yp > LOG.1yp
pw.x < PWINPUT.1zm > LOG.1zm
pw.x < PWINPUT.1zp > LOG.1zp
pw.x < PWINPUT.2xm > LOG.2xm
pw.x < PWINPUT.2xp > LOG.2xp
pw.x < PWINPUT.2ym > LOG.2ym
pw.x < PWINPUT.2yp > LOG.2yp
pw.x < PWINPUT.2zm > LOG.2zm
pw.x < PWINPUT.2zp > LOG.2zp
pw.x < PWINPUT.3xm > LOG.3xm
pw.x < PWINPUT.3xp > LOG.3xp
pw.x < PWINPUT.3ym > LOG.3ym
pw.x < PWINPUT.3yp > LOG.3yp
pw.x < PWINPUT.3zm > LOG.3zm
pw.x < PWINPUT.3zp > LOG.3zp
pw.x < PWINPUT.4xm > LOG.4xm
pw.x < PWINPUT.4xp > LOG.4xp
pw.x < PWINPUT.4ym > LOG.4ym
pw.x < PWINPUT.4yp > LOG.4yp
pw.x < PWINPUT.4zm > LOG.4zm
pw.x < PWINPUT.4zp > LOG.4zp
pw.x < PWINPUT.5xm > LOG.5xm
pw.x < PWINPUT.5xp > LOG.5xp
pw.x < PWINPUT.5ym > LOG.5ym
pw.x < PWINPUT.5yp > LOG.5yp
pw.x < PWINPUT.5zm > LOG.5zm
pw.x < PWINPUT.5zp > LOG.5zp
pw.x < PWINPUT.6xm > LOG.6xm
pw.x < PWINPUT.6xp > LOG.6xp
pw.x < PWINPUT.6ym > LOG.6ym
pw.x < PWINPUT.6yp > LOG.6yp
pw.x < PWINPUT.6zm > LOG.6zm
pw.x < PWINPUT.6zp > LOG.6zp
